# Generated by Django 3.0 on 2019-12-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=130)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Job_Title', models.CharField(blank=True, max_length=30)),
                ('Biodata', models.TextField(blank=True)),
            ],
        ),
    ]
